apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-springboot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helm-springboot.name" . }}
    helm.sh/chart: {{ include "helm-springboot.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm-springboot.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helm-springboot.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /helm
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
